nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.4.1.cjs

npmScopes:
  emmett08:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAlwaysAuth: true
    npmAuthToken: "${GITHUB_TOKEN}"
